DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
PROJECT_SOURCEFILES += stub-rdc.c

CONTIKI_PROJECT = sniffer

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../..
CONTIKI_WITH_IPV6 = 1

include $(CONTIKI)/Makefile.include
